<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            ['municipality_id' => 149, 'name' => 'ANTONIO NARIÑO'],
            ['municipality_id' => 149, 'name' => 'BARRIOS UNIDOS'],
            ['municipality_id' => 149, 'name' => 'BOSA'],
            ['municipality_id' => 149, 'name' => 'CANDELARIA'],
            ['municipality_id' => 149, 'name' => 'CHAPINERO'],
            ['municipality_id' => 149, 'name' => 'CIUDAD BOLIVAR'],
            ['municipality_id' => 733, 'name' => 'COMUNA 1'],
            ['municipality_id' => 58, 'name' => 'COMUNA 1'],
            ['municipality_id' => 408, 'name' => 'COMUNA 1'],
            ['municipality_id' => 495, 'name' => 'COMUNA 1'],
            ['municipality_id' => 725, 'name' => 'COMUNA 1'],
            ['municipality_id' => 542, 'name' => 'COMUNA 1'],
            ['municipality_id' => 615, 'name' => 'COMUNA 1'],
            ['municipality_id' => 16, 'name' => 'COMUNA 1 CENTENARIO'],
            ['municipality_id' => 739, 'name' => 'COMUNA 1 NORTE'],
            ['municipality_id' => 546, 'name' => 'COMUNA 1 OCCIDENTAL'],
            ['municipality_id' => 18, 'name' => 'COMUNA 1 PARIS'],
            ['municipality_id' => 68, 'name' => 'COMUNA 1 POPULAR'],
            ['municipality_id' => 725, 'name' => 'COMUNA 10'],
            ['municipality_id' => 542, 'name' => 'COMUNA 10'],
            ['municipality_id' => 68, 'name' => 'COMUNA 10 LA CANDELARIA'],
            ['municipality_id' => 739, 'name' => 'COMUNA 10 PROVENZA'],
            ['municipality_id' => 16, 'name' => 'COMUNA 10 QUIMBAYA'],
            ['municipality_id' => 68, 'name' => 'COMUNA 11 LAURELES'],
            ['municipality_id' => 725, 'name' => 'COMUNA 12'],
            ['municipality_id' => 18, 'name' => 'COMUNA 12 SAN FELIX'],
            ['municipality_id' => 739, 'name' => 'COMUNA 13 ORIENTAL'],
            ['municipality_id' => 68, 'name' => 'COMUNA 14 EL POBLADO'],
            ['municipality_id' => 739, 'name' => 'COMUNA 14 MORRORICO'],
            ['municipality_id' => 739, 'name' => 'COMUNA 15 CENTRO'],
            ['municipality_id' => 68, 'name' => 'COMUNA 15 GUAYABAL'],
            ['municipality_id' => 739, 'name' => 'COMUNA 17 MUTIS'],
            ['municipality_id' => 495, 'name' => 'COMUNA 2'],
            ['municipality_id' => 386, 'name' => 'COMUNA 2'],
            ['municipality_id' => 58, 'name' => 'COMUNA 2'],
            ['municipality_id' => 353, 'name' => 'COMUNA 2'],
            ['municipality_id' => 725, 'name' => 'COMUNA 2'],
            ['municipality_id' => 738, 'name' => 'COMUNA 2'],
            ['municipality_id' => 542, 'name' => 'COMUNA 2'],
            ['municipality_id' => 121, 'name' => 'COMUNA 2 JOSEFA CANELONES'],
            ['municipality_id' => 18, 'name' => 'COMUNA 2 MADERA'],
            ['municipality_id' => 739, 'name' => 'COMUNA 2 NORORIENTAL'],
            ['municipality_id' => 546, 'name' => 'COMUNA 2 ORIENTAL'],
            ['municipality_id' => 16, 'name' => 'COMUNA 2 RUFINO JOSE CUERVO'],
            ['municipality_id' => 495, 'name' => 'COMUNA 3'],
            ['municipality_id' => 738, 'name' => 'COMUNA 3'],
            ['municipality_id' => 408, 'name' => 'COMUNA 3'],
            ['municipality_id' => 615, 'name' => 'COMUNA 3'],
            ['municipality_id' => 16, 'name' => 'COMUNA 3 - ALFONSO LOPEZ'],
            ['municipality_id' => 121, 'name' => 'COMUNA 3 JOSE ANTONIO BENITEZ'],
            ['municipality_id' => 68, 'name' => 'COMUNA 3 MANRIQUE'],
            ['municipality_id' => 314, 'name' => 'COMUNA 3 NORTE'],
            ['municipality_id' => 704, 'name' => 'COMUNA 3 ORIENTE'],
            ['municipality_id' => 739, 'name' => 'COMUNA 3 SAN FRANCISCO'],
            ['municipality_id' => 18, 'name' => 'COMUNA 3 SANTA ANA'],
            ['municipality_id' => 733, 'name' => 'COMUNA 4'],
            ['municipality_id' => 16, 'name' => 'COMUNA 4 FRANCISCO DE PAULA S'],
            ['municipality_id' => 121, 'name' => 'COMUNA 4 JOSE LAURENCIO OSIO'],
            ['municipality_id' => 739, 'name' => 'COMUNA 4 OCCIDENTAL'],
            ['municipality_id' => 18, 'name' => 'COMUNA 4 SUAREZ'],
            ['municipality_id' => 546, 'name' => 'COMUNA 4 SUR'],
            ['municipality_id' => 58, 'name' => 'COMUNA 5'],
            ['municipality_id' => 408, 'name' => 'COMUNA 5'],
            ['municipality_id' => 353, 'name' => 'COMUNA 5'],
            ['municipality_id' => 386, 'name' => 'COMUNA 5'],
            ['municipality_id' => 738, 'name' => 'COMUNA 5'],
            ['municipality_id' => 68, 'name' => 'COMUNA 5 CASTILLA'],
            ['municipality_id' => 822, 'name' => 'COMUNA 5 CENTRAL'],
            ['municipality_id' => 16, 'name' => 'COMUNA 5 EL BOSQUE'],
            ['municipality_id' => 739, 'name' => 'COMUNA 5 GARCIA ROVIRA'],
            ['municipality_id' => 121, 'name' => 'COMUNA 5 JUAN JOSE RONDON'],
            ['municipality_id' => 18, 'name' => 'COMUNA 5 LA CUMBRE'],
            ['municipality_id' => 495, 'name' => 'COMUNA 6'],
            ['municipality_id' => 58, 'name' => 'COMUNA 6'],
            ['municipality_id' => 353, 'name' => 'COMUNA 6'],
            ['municipality_id' => 542, 'name' => 'COMUNA 6'],
            ['municipality_id' => 738, 'name' => 'COMUNA 6'],
            ['municipality_id' => 18, 'name' => 'COMUNA 6 BELLAVISTA'],
            ['municipality_id' => 68, 'name' => 'COMUNA 6 DOCE DE OCTUBRE'],
            ['municipality_id' => 739, 'name' => 'COMUNA 6 LA CONCORDIA'],
            ['municipality_id' => 822, 'name' => 'COMUNA 6 NORTE'],
            ['municipality_id' => 16, 'name' => 'COMUNA 6 SAN JOSE'],
            ['municipality_id' => 738, 'name' => 'COMUNA 7'],
            ['municipality_id' => 568, 'name' => 'COMUNA 7 BOCAGRANDE'],
            ['municipality_id' => 16, 'name' => 'COMUNA 7 CAFETERO'],
            ['municipality_id' => 739, 'name' => 'COMUNA 7 CIUDADELA'],
            ['municipality_id' => 822, 'name' => 'COMUNA 7 NOR ESTE'],
            ['municipality_id' => 68, 'name' => 'COMUNA 7 ROBLEDO'],
            ['municipality_id' => 542, 'name' => 'COMUNA 8'],
            ['municipality_id' => 615, 'name' => 'COMUNA 8'],
            ['municipality_id' => 16, 'name' => 'COMUNA 8 LIBERTADORES'],
            ['municipality_id' => 18, 'name' => 'COMUNA 8 NIQUIA'],
            ['municipality_id' => 673, 'name' => 'COMUNA 8 OCCIDENTAL'],
            ['municipality_id' => 822, 'name' => 'COMUNA 8 SUR'],
            ['municipality_id' => 739, 'name' => 'COMUNA 8 SUR OCCIDENTE'],
            ['municipality_id' => 68, 'name' => 'COMUNA 8 VILLA HERMOSA'],
            ['municipality_id' => 408, 'name' => 'COMUNA 9'],
            ['municipality_id' => 68, 'name' => 'COMUNA 9 BUENOS AIRES'],
            ['municipality_id' => 16, 'name' => 'COMUNA 9 FUNDADORES'],
            ['municipality_id' => 673, 'name' => 'COMUNA 9 SUR OCCIDENTAL'],
            ['municipality_id' => 739, 'name' => 'CORREGIMIENTO 1'],
            ['municipality_id' => 452, 'name' => 'CORREGIMIENTO 1 BARZALOSA'],
            ['municipality_id' => 546, 'name' => 'CORREGIMIENTO 1 BRUSELAS'],
            ['municipality_id' => 739, 'name' => 'CORREGIMIENTO 2'],
            ['municipality_id' => 495, 'name' => 'CORREGIMIENTO 2 CHARQUITO'],
            ['municipality_id' => 546, 'name' => 'CORREGIMIENTO 2 LA LAGUNA'],
            ['municipality_id' => 615, 'name' => 'CORREGIMIENTO 3'],
            ['municipality_id' => 546, 'name' => 'CORREGIMIENTO 7 GUACACALLO'],
            ['municipality_id' => 408, 'name' => 'CORREGIMIENTO 8 PUEBLO BUJO'],
            ['municipality_id' => 800, 'name' => 'CORREGIMIENTO ALTO JORDAN - GUALILO'],
            ['municipality_id' => 121, 'name' => 'CORREGIMIENTO CARACOL'],
            ['municipality_id' => 822, 'name' => 'CORREGIMIENTO CASTAÑEDA'],
            ['municipality_id' => 81, 'name' => 'CORREGIMIENTO DEL SUR'],
            ['municipality_id' => 16, 'name' => 'CORREGIMIENTO EL CAIMO'],
            ['municipality_id' => 336, 'name' => 'CORREGIMIENTO EL CUSIANA'],
            ['municipality_id' => 738, 'name' => 'CORREGIMIENTO EL LLANITO'],
            ['municipality_id' => 58, 'name' => 'CORREGIMIENTO EL MANZANILLO'],
            ['municipality_id' => 822, 'name' => 'CORREGIMIENTO LA ARENA'],
            ['municipality_id' => 715, 'name' => 'CORREGIMIENTO LA INDIA'],
            ['municipality_id' => 775, 'name' => 'CORREGIMIENTO PUENTE LLANO'],
            ['municipality_id' => 68, 'name' => 'CORREGIMIENTO SAN ANTONIO DE PRADO'],
            ['municipality_id' => 68, 'name' => 'CORREGIMIENTO SAN CRISTOBAL'],
            ['municipality_id' => 302, 'name' => 'CORREGIMIENTO SAN FELIX'],
            ['municipality_id' => 701, 'name' => 'CORREGIMIENTO SAN PEDRO'],
            ['municipality_id' => 121, 'name' => 'CORREGIMIENTO SANTA BARBARA'],
            ['municipality_id' => 68, 'name' => 'CORREGIMIENTO SANTA ELENA'],
            ['municipality_id' => 542, 'name' => 'CORREGIMIENTO VEGA LARGA'],
            ['municipality_id' => 149, 'name' => 'ENGATIVA'],
            ['municipality_id' => 149, 'name' => 'FONTIBON'],
            ['municipality_id' => 18, 'name' => 'FONTIDUEÑO'],
            ['municipality_id' => 149, 'name' => 'KENNEDY'],
            ['municipality_id' => 158, 'name' => 'LOCALIDAD 1 HISTORICA Y DEL CARIBE'],
            ['municipality_id' => 847, 'name' => 'LOCALIDAD 1 ISLA CASCAJAL.'],
            ['municipality_id' => 129, 'name' => 'LOCALIDAD 1 SUR OCCIDENTE'],
            ['municipality_id' => 158, 'name' => 'LOCALIDAD 2 LA VIRGEN Y TURISTICA'],
            ['municipality_id' => 129, 'name' => 'LOCALIDAD 2 METROPOLITANA'],
            ['municipality_id' => 129, 'name' => 'LOCALIDAD 3 SUR ORIENTE'],
            ['municipality_id' => 129, 'name' => 'LOCALIDAD 4 NORTE CENTRO HISTORICO'],
            ['municipality_id' => 129, 'name' => 'LOCALIDAD 5 RIOMAR'],
            ['municipality_id' => 149, 'name' => 'LOS MARTIRES'],
            ['municipality_id' => 149, 'name' => 'PUENTE ARANDA'],
            ['municipality_id' => 149, 'name' => 'RAFAEL URIBE URIBE'],
            ['municipality_id' => 149, 'name' => 'SAN CRISTOBAL'],
            ['municipality_id' => 149, 'name' => 'SANTAFE'],
            ['municipality_id' => 149, 'name' => 'SUBA'],
            ['municipality_id' => 149, 'name' => 'SUMAPAZ'],
            ['municipality_id' => 452, 'name' => 'SUR'],
            ['municipality_id' => 149, 'name' => 'TEUSAQUILLO'],
            ['municipality_id' => 149, 'name' => 'TUNJUELITO'],
            ['municipality_id' => 149, 'name' => 'USAQUEN'],
            ['municipality_id' => 149, 'name' => 'USME'],
        ];

        foreach ($locations as $location) {
            Location::create([
                'municipality_id' => $location['municipality_id'],
                'name' => $location['name']
            ]);
        }
    }
}
